Start of all-in-one script

diff --git a/config-vscode b/config-vscode
--- a/config-vscode
+++ b/config-vscode
@@ -10,14 +10,6 @@ VSCODE_APP_PATH="/Applications/${VSCODE_APP_NAME}"
 VSCODE_COMMAND="${VSCODE_APP_PATH}/Contents/Resources/app/bin/code"
 VSCODE_SYMLINK="/usr/local/bin/code"
 
-is_supported_platform() {
-  is_platform_mac || is_platform_windows
-}
-
-check_is_homebrew_installed() {
-  command_exists "brew"
-}
-
 check_is_vscode_installed() {
   [[ -d "${VSCODE_APP_PATH}" ]]
 }
@@ -74,36 +66,6 @@ install_required_vscode_extensions() {
   install_vscode_extension "mohsen1.prettify-json"
 }
 
-if ! is_supported_platform;then
-  echo "This script won't work with your operating system. Sorry!"
-  exit 1
-fi
-
-if guard_mac "Checking for homebrew..." check_is_homebrew_installed;then
-  echo
-
-  echo "Homebrew is not installed. Follow the instructions, here:"
-  echo "  https://brew.sh/"
-
-  exit 1
-fi
-
-if guard_mac "Checking that /usr/local/bin is in PATH..." is_in_path "/usr/local/bin";then
-  echo
-
-  echo "Add /usr/local/bin to your PATH environment variable."
-  echo "You can do this yourself if you know how or you can use"
-  echo "the add-shell-config script in this repository."
-  echo
-  echo "If you choose to add-shell-script, please see README.md"
-  echo "for instructions."
-  echo
-
-  echo "After running add-shell-script you must restart the terminal."
-
-  exit 1
-fi
-
 if guard_mac "Checking for Visual Studio Code..." check_is_vscode_installed;then
   echo
 
@@ -145,9 +107,9 @@ if guard "Installing VS Code extensions..." install_required_vscode_extensions;t
   exit 1
 fi
 
-if guard "Copying VS Code settings..." copy_with_backup "./vscode/settings.json" "$(get_vscode_appdata_dir)/settings.json";then
-  echo
-  echo "Error copying VS Code settings. Find someone to ask for help."
+# if guard "Copying VS Code settings..." copy_with_backup "./vscode/settings.json" "$(get_vscode_appdata_dir)/settings.json";then
+#   echo
+#   echo "Error copying VS Code settings. Find someone to ask for help."
 
-  exit 1
-fi
+#   exit 1
+# fi
